name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - name: Checkout code
        uses: actions/checkout@v4
      - run: ls
      - uses: actions/checkout@v4
      
      

#- checkout code
#- ls
#- docker images
#- docker push
