name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - name: Checkout code
        uses: actions/checkout@v4
      - run: ls
      - name: Login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      

#- checkout code
#- ls
#- docker images
#- docker push
