name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      
      - name: Checkout code
        uses: actions/checkout@v4
        
      - run: ls

      - name: Read current version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Increment version
        run: |
          OLD_VERSION=$(cat VERSION)
          NEW_VERSION=$(echo $OLD_VERSION | awk -F. -v OFS=. '{$NF++; print}')
          echo "New version: $NEW_VERSION"
          echo $NEW_VERSION > VERSION
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit new version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add VERSION
          git commit -m "Bump version to $VERSION"
          git push
      
      - name: Login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/getting-started-github:latest
            ${{ secrets.DOCKER_USERNAME }}/getting-started-github:${{ env.VERSION }}
      
      

#- checkout code
#- ls
#- docker images
#- docker push
